INSERT INTO BOARD (BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, BOARD_ID)
VALUES (1, '그만먹고싶어요', '너무맛있어서 그만먹고싶어요', SYSDATE, 'WHY');

INSERT INTO BOARD (BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, BOARD_ID)
VALUES (2, '예약주문', '예약주문은 어디서해요?', SYSDATE, 'WHY');

INSERT INTO BOARD (BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, BOARD_ID)
VALUES (3, '현금영수증', '현금영수증 가능한가요?', SYSDATE, 'WHY');

INSERT INTO BOARD (BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, BOARD_ID)
VALUES (4, '고객 문의 1', '제품에 대한 문의 내용입니다.', SYSDATE, 'customer1');

INSERT INTO BOARD (BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, BOARD_ID)
VALUES (5, '배송 문의', '주문한 제품의 배송일을 확인하고 싶습니다.', SYSDATE, 'customer2');

INSERT INTO BOARD (BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, BOARD_ID)
VALUES (6, '환불 요청', '제품 불만족으로 환불을 신청합니다.', SYSDATE, 'customer3');

INSERT INTO BOARD (BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, BOARD_ID)
VALUES (7, '교환 요청', '제품 교환이 필요해서 신청합니다.', SYSDATE, 'customer3');


