/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package web_project_team1_aaaa;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
